background {
    path = ~/Pictures/wallpapers/default.png
    blur_passes = 2
    blur_size = 7
}

input-field {
    size = 250, 60
    position = 0, -80
    monitor =
    dots_center = true
    fade_on_empty = false
    outer_color = rgba(89b4faee)
    inner_color = rgba(1e1e2ee6)
    font_color = rgba(cdd6f4ee)
    placeholder_text = <i>Password...</i>
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M:%S")"
    color = rgba(cdd6f4ee)
    font_size = 64
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %B %d")"
    color = rgba(cdd6f4ee)
    font_size = 20
    position = 0, 80
    halign = center
    valign = center
}
